os: linux
dist: bionic

language:
    - cpp

script:
    - qmake 
    - make
    - ./tests/tests
    
cache:
    directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
notifications:
    email: false 
